# Generated by Django 5.1.1 on 2024-10-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_anonymouscustomer_customer_and_more'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='anonymous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.anonymouscustomer'),
        ),
    ]
