# Generated by Django 5.1.1 on 2024-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Street Number'),
        ),
    ]
