# Generated by Django 5.1.1 on 2024-10-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraddress_street_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Address Type'),
        ),
    ]
