# Generated by Django 5.1.1 on 2024-10-06 13:00

import core.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=core.media.models.PathAndRename()),
        ),
    ]
