# Generated by Django 5.1.1 on 2024-09-29 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_initial'),
        ('central_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVIEWING', 'Reviewing'), ('STOPPED', 'Stopped'), ('BLOCKED', 'Blocked')], default='REVIEWING', max_length=50)),
                ('online', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user', models.Model),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name')),
                ('codename', models.SlugField(max_length=100, verbose_name='Codename')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignedbranches',
            name='branches',
            field=models.ManyToManyField(related_name='central_staffs', to='branches.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='assignedbranches',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_branches', to='central_users.centraluser', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='centraluser',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='central_users.grade'),
        ),
        migrations.CreateModel(
            name='WorkPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start', models.TimeField(verbose_name='Start Time')),
                ('end', models.TimeField(verbose_name='End Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_periods', to='central_users.centraluser', verbose_name='Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
