# Generated by Django 5.1.1 on 2024-09-29 20:03

import chat.models
import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UID')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('sending_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Sending Datetime')),
                ('receiving_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Receiving Datetime')),
                ('reading_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Reading Datetime')),
                ('editing_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Editing Datetime')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('is_received', models.BooleanField(default=False, verbose_name='Is Received')),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('LOCATION', 'Location'), ('CONTACT', 'Contact'), ('VOICE', 'Voice')], default='TEXT', max_length=20, verbose_name='Type')),
                ('file', models.FileField(blank=True, null=True, upload_to=chat.models.PathAndRename(), verbose_name='File')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('sender_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Sender Location')),
                ('receiver_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Receiver Location')),
                ('old_content', models.JSONField(blank=True, null=True, verbose_name='Old Content')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
