# Generated by Django 5.1.1 on 2024-09-29 20:03

import django.contrib.gis.db.models.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Branch')),
                ('serial_number', models.CharField(max_length=15, verbose_name='Serial Number')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('license', models.CharField(max_length=100, verbose_name='License')),
                ('license_file', models.FileField(upload_to='licenses', verbose_name='License File')),
                ('commercial_register', models.CharField(max_length=100, verbose_name='Commercial Register')),
                ('commercial_register_file', models.FileField(upload_to='commercial_registers', verbose_name='Commercial Register')),
                ('tax_number', models.CharField(max_length=100, verbose_name='Tax Number')),
                ('tax_file', models.FileField(upload_to='tax_files', verbose_name='Tax File')),
                ('iban', models.CharField(max_length=100, verbose_name='IBAN')),
                ('iban_number', models.CharField(max_length=100, verbose_name='IBAN Number')),
                ('iban_file', models.FileField(upload_to='iban_files', verbose_name='IBAN File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('delivery_type', models.CharField(choices=[('FAST', 'Fast'), ('SCHEDULED', 'Scheduled'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('zone_type', models.CharField(choices=[('ALL_TIME', 'All Time'), ('CUSTOM_TIME', 'Custom Time')], default='ALL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name')),
                ('day_of_week', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
