# Generated by Django 5.1.1 on 2024-09-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.region'),
        ),
        migrations.AddField(
            model_name='branchservicezone',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='branchservicezone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.geographicalzone'),
        ),
        migrations.AddField(
            model_name='branch',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='branches', through='branches.BranchServiceZone', to='settings.geographicalzone'),
        ),
        migrations.AddField(
            model_name='deliverytimeslot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='branches.branchservicezone'),
        ),
    ]
