# Generated by Django 5.1.1 on 2024-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservicezone',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name'),
        ),
    ]
