# Generated by Django 5.1.1 on 2024-10-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branchservicezone_name_en'),
        ('settings', '0002_alter_geographicalzone_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('generalsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settings.generalsettings')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='branches.branch')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('settings.generalsettings',),
        ),
    ]
