# Generated by Django 5.1.1 on 2024-10-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='offer',
        ),
        migrations.AddField(
            model_name='promotionanalytics',
            name='content_type',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionanalytics',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
