# Generated by Django 5.1.1 on 2024-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryshelf',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='primaryshelf',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='English Name'),
        ),
    ]
