# Generated by Django 5.1.1 on 2024-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_products', '0003_primaryshelf_name_primaryshelf_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='quantity_for_marketing',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
