# Generated by Django 5.1.1 on 2024-10-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_products', '0007_remove_product_number_remove_product_sq_and_more'),
        ('products', '0010_remove_group_number_remove_product_barcodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='products.productunit', verbose_name='Product'),
        ),
    ]
