# Generated by Django 5.1.1 on 2024-10-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_products', '0008_alter_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinggroup',
            name='number',
            field=models.CharField(default=22, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
