# Generated by Django 5.1.2 on 2024-10-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_products', '0010_product_price_gross_product_price_gross_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
