# Generated by Django 5.1.1 on 2024-10-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_anonymouscustomer_browsingkey_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsingkey',
            name='anonymous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.anonymouscustomer'),
        ),
    ]
