# Generated by Django 5.1.1 on 2024-10-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_anonymouscustomer_customer_and_more'),
        ('products', '0005_alter_barcode_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscustomer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='anonymous_favorites', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='customers_favorites', to='products.product'),
        ),
    ]
