# Generated by Django 5.1.1 on 2024-09-29 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_draft', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('CUSTOM', 'Custom'), ('PRODUCT', 'Product'), ('OFFER', 'Offer')], default='CUSTOM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('shape', models.CharField(choices=[('BAR', 'Bar'), ('POPUP', 'Popup'), ('CARD', 'Card'), ('PRODUCT_CARD', 'Product Card'), ('GROUP_CARD', 'Group Card'), ('CATEGORY_CARD', 'Category Card')], default='BAR', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('show_in_order_summary', models.BooleanField(default=False)),
                ('show_in_cart', models.BooleanField(default=False)),
                ('show_in_checkout', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
