# Generated by Django 5.1.1 on 2024-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
    ]
