# Generated by Django 5.1.1 on 2024-09-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchuser',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='preparer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'base_manager_name': 'objects'},
        ),
    ]
