# Generated by Django 5.1.1 on 2024-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers_classification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pack",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pack",
            name="name",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pack",
            name="name_en",
            field=models.CharField(blank=True, null=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pack",
            name="per",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group"),
                    ("CATEGORY", "Category"),
                    ("SUPPLIER", "Supplier"),
                    ("PRODUCT", "Product"),
                    ("MIXIN", "Mixin"),
                ],
                default="MIXIN",
                max_length=10,
            ),
        ),
    ]
