# Generated by Django 5.1.1 on 2024-10-06 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_classification', '0002_pack_description_pack_description_en_pack_name_and_more'),
        ('products', '0004_category_number_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='per',
            field=models.CharField(choices=[('GROUP', 'Group'), ('CATEGORY', 'Category'), ('SUPPLIER', 'Supplier'), ('PRODUCT', 'Product'), ('BRAND', 'Brand'), ('MIXIN', 'Mixin')], default='MIXIN', max_length=10),
        ),
        migrations.CreateModel(
            name='PackBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_packs', to='products.brand')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_brands', to='offers_classification.pack')),
            ],
            options={
                'unique_together': {('pack', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='packs', through='offers_classification.PackBrand', to='products.brand', verbose_name='Brands'),
        ),
    ]
