# Generated by Django 5.1.1 on 2024-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_classification', '0003_alter_pack_per_packbrand_pack_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='default_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
