# Generated by Django 5.1.1 on 2024-10-01 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
        ('orders', '0012_cart_location_order_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcoupon',
            old_name='commission_percentage',
            new_name='commission_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount_currency',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percenatage',
        ),
        migrations.RemoveField(
            model_name='marketingcoupon',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='marketingcoupon',
            name='commission_amount_currency',
        ),
        migrations.AddField(
            model_name='coupon',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Value'),
        ),
        migrations.AddField(
            model_name='offer',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Min Purchase Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='work_with_coupon',
            field=models.BooleanField(default=False, verbose_name='Work with Coupon'),
        ),
        migrations.AddField(
            model_name='offer',
            name='work_with_offer',
            field=models.BooleanField(default=False, verbose_name='Work with Other Offer'),
        ),
        migrations.AddField(
            model_name='offercondition',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AbandonedCartOffer',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.offer')),
                ('carts', models.ManyToManyField(related_name='abandoned_cart_offers', to='orders.cart')),
            ],
            options={
                'abstract': False,
            },
            bases=('discounts.offer',),
        ),
    ]
