# Generated by Django 5.1.1 on 2024-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_offer_units'),
        ('products', '0003_alter_productprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.unit'),
        ),
    ]
