# Generated by Django 5.1.1 on 2024-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_cart_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('PREPARING', 'Preparing'), ('PREPARED', 'Prepared'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('CHECKING', 'Checking'), ('CHECKED', 'Checked'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('DONE', 'Done'), ('RETURNED', 'Returned'), ('CANCELED', 'Canceled'), ('TRANSFERRED', 'Transferred')], default='PENDING', max_length=20),
        ),
    ]
