# Generated by Django 5.1.1 on 2024-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_delivery_price_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delayed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
