# Generated by Django 5.1.1 on 2024-10-01 17:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options'),
        ('orders', '0011_alter_order_cart'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_preparing_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cart',
            name='browsing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='customers.browsingkey'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.useraddress'),
        ),
    ]
