# Generated by Django 5.1.1 on 2024-10-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_anonymouscustomer_customer_and_more'),
        ('orders', '0014_alter_cart_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customers.anonymouscustomer'),
        ),
    ]
