# Generated by Django 5.1.1 on 2024-10-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0015_cart_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='discount_value',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='discount_value_currency',
            new_name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_items_prices', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='discount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_discounts', to='contenttypes.contenttype'),
        ),
    ]
