# Generated by Django 5.1.1 on 2024-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productcost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'unit'), name='unique_product_unit'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'unit', 'pricing_group'), name='unique_product_pricing_group'),
        ),
    ]
