# Generated by Django 5.1.1 on 2024-10-07 18:01

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file'),
        ('products', '0004_category_number_alter_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'verbose_name': 'Barcode', 'verbose_name_plural': 'Barcodes'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='pricinggroup',
            options={'verbose_name': 'Pricing Group', 'verbose_name_plural': 'Pricing Groups'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcost',
            options={'verbose_name': 'Product Cost', 'verbose_name_plural': 'Product Costs'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='default_image',
            field=models.CharField(blank=True, null=True, verbose_name='Default Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='brands', to='media.media', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_image',
            field=models.CharField(blank=True, null=True, verbose_name='Default Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='categories', to='media.media', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_barcodes', to='products.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='groups', to='media.media', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.group', verbose_name='Parent Group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit Margin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('None', 'None')], default='None', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='SAR', max_digits=14, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='SAR', max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='codename',
            field=models.SlugField(unique=True, verbose_name='Codename'),
        ),
    ]
