# Generated by Django 5.1.1 on 2024-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productfeature_remove_productcost_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productprice',
            name='unique_product_pricing_group',
        ),
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'pricing_group'), name='unique_product_pricing_group'),
        ),
    ]
