# Generated by Django 5.1.1 on 2024-10-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('None', 'None')], default='None', max_length=255, verbose_name='Type'),
        ),
    ]
