# Generated by Django 5.1.1 on 2024-10-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_group_number_remove_product_barcodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.product', to_field='sq'),
        ),
    ]
