# Generated by Django 5.1.1 on 2024-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file'),
        ('products', '0011_alter_productunit_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'Product Unit', 'verbose_name_plural': 'Product Units'},
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'unit'), name='unique_product_unit'),
        ),
    ]
