# Generated by Django 5.1.1 on 2024-10-14 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productunit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
