# Generated by Django 5.1.1 on 2024-10-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file'),
        ('products', '0014_alter_productunit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_image',
            field=models.CharField(blank=True, null=True, verbose_name='Default Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='media.media', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products_units', to='media.media', verbose_name='Images'),
        ),
    ]
