# Generated by Django 5.1.1 on 2024-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_product_default_image_product_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricinggroup",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productprice",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productunit",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unit",
            name="number",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
